#+TITLE: Linking Biomedical Data for AI-Driven Health Research in Africa

#+OPTIONS: toc:nil title:t num:nil author:nil date:nil
#+latex_class: article
#+latex_class_options: [notitlepage,11pt]
#+CITE_EXPORT: biblatex
#+INCLUDE: config.org
#+bibliography: proposal.bib

@@latex:\vspace{-5em}@@
* Team Details
| **Team Name:**    | /Team LOD (Linked Open Data) Avengers/       |
|-------------------+----------------------------------------------|
| **Team Members:** | /B.  Munyoki Kilyungi/ me@bonfacemunyoki.com |
|                   | /S. Solomon Darnell/ ssd2023@nyeusi.tech     |


* Introduction

Our proposal submission aims to address the challenges faced by biomedical AI/ML research due to the limited accessibility and fragmented nature of data.  Even public datasets often lack clear relationships between data points, thus hindering the full potential of AI/ML.  Our proposal aims to enhance biomedical data accessibility, annotation, and interoperability using Linked Data Principles.  We believe that transforming data into Linked Data will empower researchers to harness the full potential of AI in health research, particularly in Africa's context.

* Objectives

- Extend our public internally developed self-documenting DSL available at https://git.genenetwork.org/gn-transform-databases/, to support the conversion of data from various formats, not limited to SQL, into RDF.
- Demonstrate the process of converting data into RDF by showcasing transformations with publicly available datasets, with a preference for medical data sourced from Africa.
- Illustrate the integration of Linked Data within an LLM (Large Language Model).
- Package the aforementioned DSL to upstream Guix so that it becomes available to the wider scientific community.  

* Proposed Approach

- /Data Annotation/: Explore suitable ontologies for annotating data or consider developing custom ontologies to model our specific dataset.
- /Linked Data Transformation/: Use our DSL to transform data into RDF directly from the source and subsequently upload it to a Virtuoso instance for the purpose of demonstration.
- /Machine Learning and AI Integration/: Upload the transformed linked data to an LLM and assess it's performance.

* Expected Outcomes:
Our participation in this hackathon is expected to yield the following outcomes:

- An improved DSL designed to convert data from various formats into RDF, which will be either incorporated into Guix upstream or be under review by maintainers.
- A demonstration of how our DSL can be used to annotate data from different formats while transforming it into triple stores.
- A showcase of the integration of machine learning and AI techniques with Linked Data.  

* Conclusion

We are excited to participate in this hackathon and look forward to this proposal's review and hopefully possible collaboration with fellow participants.  Our team is committed to demonstrating the potential of Linked Data in transforming biomedical research, and we believe that our contribution will pave the way for more accessible and impactful health research in Africa.

# local variables:
# eval: (progn (require 'ox-extra) (ox-extras-activate '(ignore-headlines)))
# end:
