#+TITLE: Unlocking Biomedical Data for AI Health Research in Africa Using GeneNetwork as an Example

#+OPTIONS: toc:nil title:t num:nil author:nil date:nil
#+latex_class: article
#+latex_class_options: [notitlepage,11pt]
#+CITE_EXPORT: biblatex
#+INCLUDE: config.org
#+bibliography: proposal.bib
#+keywords: Genenetwork2, SQL, RDF, data interoperability, data integration, genetic research.
@@latex:\vspace{-5em}@@

\begin{center}
Bonface Munyoki Kilyungi | bonface.kilyungi@strathmore.edu \\
\textsc{Adm No:} 070707
\end{center}

\textsc{Keywords:} Genenetwork2, SQL, RDF, data interoperability, data integration, genetic research.

* Introduction
Genenetwork2 is a powerful open-source software platform for analyzing genetic data [cite:@mulligan2017genenetwork;@sloan2016genenetwork].  It provides a range of tools and resources for analyzing, visualizing, and storing genetic data.  However, its underlying SQL database can be complex and difficult to use and lacks interoperability with other systems.  This dissertation proposes to port Genenetwork2's SQL database to the Resource Description Framework (RDF), a widely-used semantic data model that can provide several benefits over SQL.  Representing Genenetwork2's data in RDF will enable: more flexible querying, data integration, and reasoning capabilities, as well as provide better support for the Linked Data and Semantic Web standards.

* Problem Statement

The current SQL database of Genenetwork2 has several limitations, such as its lack of support for complex data types, reasoning, and ontologies.  These limitations make it difficult to integrate and query Genenetwork2's data with other sources, and to perform advanced analysis tasks, such as inferencing and querying by example.

\clearpage

* Research Objectives

The main objective of this dissertation is to port Genenetwork2's SQL database to RDF, and to evaluate the potential benefits and challenges of this approach.  The specific research objectives are:

1.  Evaluate the potential benefits and challenges of porting the database to RDF, including its impact on data interoperability, integration, and security.

2.  Develop a detailed plan for the porting process, including the steps, tools, and resources

* Expected Results

The expected results of this dissertation are:

1.  A thorough analysis of Genenetwork2's current SQL database.

2.  A detailed evaluation of the potential benefits and challenges of porting the database to RDF, including its impact on data interoperability, integration, and security.

3.  A proof-of-concept implementation of the RDF-based Genenetwork2 database, including the necessary scripts and tools for data migration and integration.

4.  An assessment of the performance and interoperability of the RDF-based database.

5.  An evaluation of the potential benefits of the RDF-based Genenetwork2 for users and the broader genetics community, including its impact on data integration, analysis, and sharing.

The resulting RDF-based Genenetwork2 will be a valuable resource for the genomics research community, providing more flexible and interoperable data management and analysis capabilities.

\clearpage

* References                                                         :ignore:
#+print_bibliography:
# local variables:
# eval: (progn (require 'ox-extra) (ox-extras-activate '(ignore-headlines)))
# end:
