name: Generate pdf

# Run actions when pushing to the main branch or when you create a
# PR against it
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile dissertation defense      
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          make -C proposal-defense/
          make -C dissertation/
          mv proposal-defense/main.pdf proposal-defense/proposal-defense.pdf          
          mv dissertation/main.pdf dissertation/dissertation.pdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: |
          proposal-defense/proposal-defense.pdf
          dissertation/dissertation.pdf

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Dissertation---PDF
        files: |
          proposal-defense/proposal-defense.pdf
          dissertation/dissertation.pdf
